chargerEff: 0.94
chargerPower: 75
ebMaxKwh: 675
emChargeEff: 0.9
emChargePower: 500
emDischargeEff: 0.9
emDischargePower: 500
emMaxKwh: 1000
filename: flex_test 38
gridMaxPower: 500
numBuses: 10
numChargers: 3
routes:
- 183
- 22
- 3
- 138
- 265
- 122
- 208
- 36
- 96
- 23
runType: static
solarMaxPower: 250
